ifeq ($(BOARD_HAS_GPS),true)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw

LOCAL_C_INCLUDES += \
	$(LOCAL_PATH)/../include

LOCAL_SRC_FILES := gps.c

LOCAL_SHARED_LIBRARIES := liblog libcutils libhardware
LOCAL_STATIC_LIBRARIES := libgps-$(TARGET_BOOTLOADER_BOARD_NAME)

LOCAL_MODULE := gps.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)

endif
